### ISSUE TITLE
Confusion about license

### ISSUE THREAD

**Issue by mzillgith** [edimetia3d/OPC-Client-X64#6]
Hi,
I am confused about the license of the project. Whilst the source code files tell it is LGPL the license.txt file tells it is GPLv3. As I understood the GPL it is ok to convert the license from LGPL to GPL but not the other way around. So my question is was this change to GPLv3 intended. With GPLv3 I cannot use it in my project.

**Comment by edimetia3d** [comment]
Sorry, I didn't notice this before,  It has changed to LGPLv3.

and, I have been busy for months, so I didn't handle with other issues. I think I could  deal these issues after Sept., when my stuffs should be finished.

**Comment by mzillgith** [comment]
Thanks for clarification.
